@extends('layouts.app')
@section('css')
@include('landingpage.maincss')
@endsection
@section('content')
    @include('landingpage.contents') 
@endsection
@section('scripts')
@include('landingpage.mainscript')
@endsection