@extends('layouts.app')
@section('css')
@include('landingpage.maincss')
@endsection
@section('contents')
<h4>contact</h4>
@endsection
@section('scripts')
@include('landingpage.mainscript')
@endsection